/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.bsuir.courseproject.client;

import by.bsuir.courseproject.dulko.database.model.Instructor;
import by.bsuir.courseproject.dulko.database.model.Programm;
import by.bsuir.courseproject.dulko.database.model.Schedule;
import by.bsuir.courseproject.dulko.logic.AddScheduleLogic;
import by.bsuir.courseproject.dulko.logic.InstructorLogic;
import by.bsuir.courseproject.dulko.logic.ProgrammLogic;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Евгения
 */
public class AddScheduleForm extends javax.swing.JFrame {

    private String login = null;
    private AddScheduleLogic asl = null;
    private InstructorLogic il = null;
    private ProgrammLogic pl = null;
    private Schedule schedule;

    /**
     * Creates new form AddScheduleForm
     */
    private void initForm() {
        initComponents();
        try {
            asl = Start.getEntityManager().getAddScheduleManager();
            pl = Start.getEntityManager().getProgrammManager();
            il = Start.getEntityManager().getInstructorManager();
        } catch (RemoteException ex) {
            Logger.getLogger(AddScheduleForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Instructor> instructors = il.getAllInstructors();
        List<String> instructorsSurname = new ArrayList<>();
        for (Instructor i : instructors) {
            instructorsSurname.add(i.getSurname());
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(instructorsSurname.toArray()));
        List<Programm> programms = pl.getAllProgramms();
        List<String> nameProgramm = new ArrayList<>();
        for (Programm i : programms) {
            nameProgramm.add(i.getNameProgramm());
        }
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(nameProgramm.toArray()));
        List<String> idWeekday = new ArrayList<>();
        idWeekday.add("пн");
        idWeekday.add("вт");
        idWeekday.add("ср");
        idWeekday.add("чт");
        idWeekday.add("пт");
        idWeekday.add("сб");
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(idWeekday.toArray()));
    }

    public AddScheduleForm(String login) {
        this.login = login;
        initForm();
        schedule = new Schedule();
    }

    public AddScheduleForm(Schedule schedule, String login) {
        initForm();
        this.login = login;
        this.schedule = schedule;
        switch (schedule.getWeekday()) {
            case "1": jComboBox3.setSelectedIndex(0); break;
                case "2": jComboBox3.setSelectedIndex(1); break;
                    case "3": jComboBox3.setSelectedIndex(2); break;
                        case "4": jComboBox3.setSelectedIndex(3); break;
                            case "5": jComboBox3.setSelectedIndex(4); break;
                                case "6": jComboBox3.setSelectedIndex(5); break;
                            }
        jTextField2.setText(schedule.getTime());
        jComboBox2.setSelectedItem(pl.getNameProgramm(schedule.getIdProgramm()));
        jComboBox1.setSelectedItem(il.getSurname(schedule.getIdInstructor()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("День недели:");

        jLabel3.setText("Время:");

        jLabel4.setText("Программа:");

        jLabel6.setText("Инструктор:");

        jButton1.setText("Сохранить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Отмена");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch ((String) jComboBox3.getSelectedItem()) {
            case "пн": this.schedule.setWeekday("1"); break;
                case "вт": this.schedule.setWeekday("2"); break;
                    case "ср": this.schedule.setWeekday("3"); break;
                        case "чт": this.schedule.setWeekday("4"); break;
                            case "пт": this.schedule.setWeekday("5"); break;
                                case "сб": this.schedule.setWeekday("6"); break;
                            }
            this.schedule.setTime(jTextField2.getText());
            this.schedule.setIdProgramm(pl.getProgrammId((String) jComboBox2.getSelectedItem()));
            this.schedule.setIdInstructor(il.getInstructorId((String) jComboBox1.getSelectedItem()));
            asl.saveSchedule(schedule);
            dispose();
            ScheduleForm scheduleForm = new ScheduleForm(login);
            scheduleForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ScheduleForm scheduleForm = new ScheduleForm(login);
        scheduleForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
