/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.bsuir.courseproject.client;

import by.bsuir.courseproject.dulko.database.model.Instructor;
import by.bsuir.courseproject.dulko.database.model.Schedule;
import by.bsuir.courseproject.dulko.database.model.Workout;
import by.bsuir.courseproject.dulko.logic.CongestionInstructorsLogic;
import by.bsuir.courseproject.dulko.logic.InstructorLogic;
import by.bsuir.courseproject.dulko.logic.ScheduleLogic;
import by.bsuir.courseproject.dulko.logic.WorkoutLogic;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Евгения
 */
public class CongestionInstructorsForm extends javax.swing.JFrame {

    private String login = null;
    private CongestionInstructorsLogic cil = null;
    private InstructorLogic il = null;
    private List<Workout> workoutList = null;
    private List<Schedule> scheduleList = null;
    private WorkoutLogic wl = null;
    private Schedule schedule;
    private Instructor instructor;
    private ScheduleLogic sl;

    /**
     * Creates new form CongestionInstructorsForm
     */
    public class ImagePanel extends JPanel {

        private BufferedImage image;

        public ImagePanel() throws IOException {
            image = ImageIO.read(new File("C:\\Users\\Евгения\\Documents\\NetBeansProjects\\ClientCP\\Image\\11.jpg"));
        }

        @Override
        protected void paintComponent(Graphics g) {
            g.drawImage(image, 0, 0, null);
        }
    }

    public CongestionInstructorsForm(String login) {
        initComponents();
        this.login = login;
        try {
            wl = Start.getEntityManager().getWorkoutManager();
            cil = Start.getEntityManager().getCongestionInstructorsManager();
            sl = Start.getEntityManager().getScheduleManager();
            il = Start.getEntityManager().getInstructorManager();
        } catch (RemoteException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jPanel1 = new ImagePanel();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            jToggleButton1 = new javax.swing.JToggleButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Загруженность интсрукторов");
            setPreferredSize(new java.awt.Dimension(1055, 512));
            setResizable(false);

        }catch(IOException e) {
            e.printStackTrace();
        }
        jPanel1.setMaximumSize(new java.awt.Dimension(1055, 512));
        jPanel1.setMinimumSize(new java.awt.Dimension(1055, 512));
        jPanel1.setPreferredSize(new java.awt.Dimension(1055, 512));

        jTable1.setBackground(new java.awt.Color(255, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 600));
        jTable1.setPreferredSize(new java.awt.Dimension(375, 600));
        jScrollPane1.setViewportView(jTable1);

        jToggleButton1.setText("OK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        MainForm mainForm = new MainForm(login);
        mainForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void refresh() {
        workoutList = wl.getAllWorkouts();
        scheduleList = sl.getAllScheduls();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[scheduleList.size()][5],
                new String[]{
                    "#", "Фамилия", "День недели", "Время", "Количество человек"
                }
        ));
        jTable1.getColumnModel().getColumn(0).setMaxWidth(30);

        for (int j = 0; j < scheduleList.size(); j++) {
            jTable1.getModel().setValueAt(j + 1, j, 0);
            jTable1.getModel().setValueAt(((Instructor) il.getInstructorById(scheduleList.get(j).getIdInstructor())).getSurname(), j, 1);
            switch (scheduleList.get(j).getWeekday()) {
            case "1": jTable1.getModel().setValueAt("пн", j, 2); break;
                case "2": jTable1.getModel().setValueAt("вт", j, 2); break;
                    case "3": jTable1.getModel().setValueAt("ср", j, 2); break;
                        case "4": jTable1.getModel().setValueAt("чт", j, 2); break;
                            case "5": jTable1.getModel().setValueAt("пт", j, 2); break;
                                case "6": jTable1.getModel().setValueAt("сб", j, 2); break;
                            }
            jTable1.getModel().setValueAt(scheduleList.get(j).getTime(), j, 3);
            jTable1.getModel().setValueAt(cil.getCongestionInstructors(scheduleList.get(j)), j, 4);
            jTable1.setAutoCreateRowSorter(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
