/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.bsuir.courseproject.client;

import by.bsuir.courseproject.dulko.database.model.Programm;
import by.bsuir.courseproject.dulko.database.model.Workout;
import by.bsuir.courseproject.dulko.logic.ClientLogic;
import by.bsuir.courseproject.dulko.logic.InstructorLogic;
import by.bsuir.courseproject.dulko.logic.ProgrammLogic;
import by.bsuir.courseproject.dulko.logic.ScheduleLogic;
import by.bsuir.courseproject.dulko.logic.WorkoutLogic;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Евгения
 */
public class WorkoutForm extends javax.swing.JFrame {

    private String login = null;
    private List<Workout> workoutList;
    private Workout workout;
    private WorkoutLogic wl = null;
    private ClientLogic cl = null;
    private InstructorLogic il = null;
    private ProgrammLogic pl = null;
    private ScheduleLogic sl = null;

    public class ImagePanel extends JPanel {

        private BufferedImage image;

        public ImagePanel() throws IOException {
            image = ImageIO.read(new File("C:\\Users\\Евгения\\Documents\\NetBeansProjects\\ClientCP\\Image\\11.jpg"));
        }

        @Override
        protected void paintComponent(Graphics g) {
            g.drawImage(image, 0, 0, null);
        }
    }

    public WorkoutForm(String login) {
        initComponents();
        try {
            this.login = login;
            wl = Start.getEntityManager().getWorkoutManager();
            cl = Start.getEntityManager().getClientManager();
            il = Start.getEntityManager().getInstructorManager();
            pl = Start.getEntityManager().getProgrammManager();
            sl = Start.getEntityManager().getScheduleManager();

        } catch (RemoteException ex) {
            Logger.getLogger(WorkoutForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Programm> programms = pl.getAllProgramms();
        List<String> nameProgramm = new ArrayList<>();
        for (Programm i : programms) {
            nameProgramm.add(i.getNameProgramm());
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(nameProgramm.toArray()));
        refresh();
    }

    private void refresh() {
        jButton1.setEnabled(false);
        jButton1.setText("Выведены все занятия");
        if (login.equals("admin"))
            workoutList = wl.getAllWorkouts();
        else workoutList = wl.getWorkoutsIdByClient(cl.getClientWhereLogin(login).getId());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[workoutList.size()][8],
                new String[]{
                    "#", "Фамилия", "Имя", "Отчество", "День недели", "Время", "Программа", "Инструктор"
                }
        ));
        jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        for (int j = 0; j < workoutList.size(); j++) {
            jTable1.getModel().setValueAt(j + 1, j, 0);
            jTable1.getModel().setValueAt(cl.getSurname(workoutList.get(j).getIdClient()), j, 1);
            jTable1.getModel().setValueAt(cl.getName(workoutList.get(j).getIdClient()), j, 2);
            jTable1.getModel().setValueAt(cl.getLastname(workoutList.get(j).getIdClient()), j, 3);
            switch (sl.getWeekday(workoutList.get(j).getIdSchedule())) {
            case "1": jTable1.getModel().setValueAt("пн", j, 4); break;
                case "2": jTable1.getModel().setValueAt("вт", j, 4); break;
                    case "3": jTable1.getModel().setValueAt("ср", j, 4); break;
                        case "4": jTable1.getModel().setValueAt("чт", j, 4); break;
                            case "5": jTable1.getModel().setValueAt("пт", j, 4); break;
                                case "6": jTable1.getModel().setValueAt("сб", j, 4); break;
                            }
            jTable1.getModel().setValueAt(sl.getTime(workoutList.get(j).getIdSchedule()), j, 5);
            jTable1.getModel().setValueAt(pl.getNameProgramm(workoutList.get(j).getIdProgramm()), j, 6);
            jTable1.getModel().setValueAt(il.getSurname(sl.getIdInstructor(workoutList.get(j).getIdSchedule())), j, 7);
            jTable1.setAutoCreateRowSorter(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jPanel1 = new ImagePanel();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            jToggleButton1 = new javax.swing.JToggleButton();
            jLabel1 = new javax.swing.JLabel();
            jComboBox1 = new javax.swing.JComboBox();
            jButton1 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Занятия");

        } catch(IOException e) {
            e.printStackTrace();
        }

        jTable1.setBackground(new java.awt.Color(255, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 600));
        jTable1.setPreferredSize(new java.awt.Dimension(600, 600));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jToggleButton1.setText("OK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Вывести занятия по программе:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jButton1.setText("Вывести все");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(319, 319, 319)
                        .addComponent(jToggleButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        MainForm mainForm = new MainForm(login);
        mainForm.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0) {
            workout = workoutList.get(row);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        jButton1.setText("Вывести все занятия");
                 
            if (login.equals("admin"))
            workoutList = wl.getWorkoutsIdByProgramm(pl.getProgrammId((String) jComboBox1.getSelectedItem()));
        else workoutList = wl.getWorkoutsIdByProgrammByIdClient(pl.getProgrammId((String) jComboBox1.getSelectedItem()), cl.getClientWhereLogin(login).getId());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[workoutList.size()][8],
                new String[]{
                    "#", "Фамилия", "Имя", "Отчество", "День недели", "Время", "Программа", "Инструктор"
                }
        ));
        jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        for (int j = 0; j < workoutList.size(); j++) {
            jTable1.getModel().setValueAt(j + 1, j, 0);
            jTable1.getModel().setValueAt(cl.getSurname(workoutList.get(j).getIdClient()), j, 1);
            jTable1.getModel().setValueAt(cl.getName(workoutList.get(j).getIdClient()), j, 2);
            jTable1.getModel().setValueAt(cl.getLastname(workoutList.get(j).getIdClient()), j, 3);
            switch (sl.getWeekday(workoutList.get(j).getIdSchedule())) {
            case "1": jTable1.getModel().setValueAt("пн", j, 4); break;
                case "2": jTable1.getModel().setValueAt("вт", j, 4); break;
                    case "3": jTable1.getModel().setValueAt("ср", j, 4); break;
                        case "4": jTable1.getModel().setValueAt("чт", j, 4); break;
                            case "5": jTable1.getModel().setValueAt("пт", j, 4); break;
                                case "6": jTable1.getModel().setValueAt("сб", j, 4); break;
                            }
            jTable1.getModel().setValueAt(sl.getTime(workoutList.get(j).getIdSchedule()), j, 5);
            jTable1.getModel().setValueAt(pl.getNameProgramm(workoutList.get(j).getIdProgramm()), j, 6);
            jTable1.getModel().setValueAt(il.getSurname(sl.getIdInstructor(workoutList.get(j).getIdSchedule())), j, 7);
            jTable1.setAutoCreateRowSorter(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (workout != null) {
            wl.deleteWorkout(workout);
            refresh();
            JOptionPane.showMessageDialog(null, "Запись успешно удалена.");
        } else {
            JOptionPane.showMessageDialog(null, "Выберите запись для удаления.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
